/**
 * Classification categories for incoming messages.
 * Claude assigns one of these based on message content.
 */
export type MessageCategory =
	| "article"     // Links, blog posts, news articles
	| "question"    // Someone asking you something that needs a response
	| "task"        // Action items, requests, todos
	| "update"      // Status updates, FYIs, notifications
	| "reference"   // Reference material, docs, specs
	| "idea"        // Ideas, brainstorms, suggestions
	| "conversation" // General chat, social, not actionable
	| "unclassified"; // Fallback when classification fails

/**
 * Priority level for actionable messages.
 */
export type MessagePriority = "high" | "medium" | "low" | "none";

/**
 * Represents a raw incoming message before classification.
 */
export interface InboxMessage {
	/** Original filename in the inbox folder */
	filename: string;
	/** Full file path within the vault */
	filepath: string;
	/** Raw markdown content of the message file */
	content: string;
	/** Frontmatter parsed from the file, if any */
	frontmatter: Record<string, unknown>;
	/** When the file was created/detected */
	receivedAt: Date;
}

/**
 * A message after Claude has classified it.
 */
export interface ClassifiedMessage extends InboxMessage {
	/** Category assigned by Claude */
	category: MessageCategory;
	/** Short summary generated by Claude */
	summary: string;
	/** Tags suggested by Claude */
	tags: string[];
	/** Where Claude suggests filing this (relative vault path) */
	suggestedPath: string;
	/** Confidence score 0-1 */
	confidence: number;
	/** Priority level for actionable items */
	priority: MessagePriority;
	/** People mentioned or involved */
	people: string[];
	/** Dates/deadlines extracted from the message */
	dates: string[];
	/** Suggested next actions (for tasks/questions) */
	actions: string[];
	/** Fetched URL metadata (titles, descriptions) */
	urlMeta: Array<{
		url: string;
		title: string;
		description: string;
		siteName: string;
	}>;
	/** Short topic label for filenames (e.g. "auth service PR") */
	topic: string;
}

/**
 * Plugin settings persisted in Obsidian's data.json.
 */
export interface SignalInboxSettings {
	/** Path to the inbox folder within the vault (relative) */
	inboxPath: string;
	/** Path to the processed/archive folder (relative) */
	archivePath: string;
	/** Claude API key for classification */
	claudeApiKey: string;
	/** Claude model to use */
	claudeModel: string;
	/** Whether to auto-classify new messages */
	autoClassify: boolean;
	/** Whether to auto-file after classification (vs. requiring confirmation) */
	autoFile: boolean;
	/** Whether to fetch URL content for richer classification */
	fetchUrls: boolean;
	/** Minimum confidence to auto-file (below this, messages go to archive instead) */
	confidenceThreshold: number;
	/** Maximum API calls per day (0 = unlimited) */
	dailyApiLimit: number;
	/** Polling interval in seconds for checking new files */
	pollIntervalSeconds: number;
	/** Category-to-folder mapping: where each category gets filed */
	categoryFolders: Record<MessageCategory, string>;
	/** Custom classification prompt override */
	classificationPrompt: string;
	/** Internal: API calls made today */
	_apiCallsToday: number;
	/** Internal: date string for API call tracking (YYYY-MM-DD) */
	_apiCallsDate: string;
}

export const DEFAULT_SETTINGS: SignalInboxSettings = {
	inboxPath: "_inbox/signal",
	archivePath: "_inbox/processed",
	claudeApiKey: "",
	claudeModel: "claude-sonnet-4-20250514",
	autoClassify: true,
	autoFile: false,
	fetchUrls: true,
	confidenceThreshold: 0.6,
	dailyApiLimit: 100,
	pollIntervalSeconds: 10,
	categoryFolders: {
		article: "wiki/sources",
		question: "inbox/questions",
		task: "inbox/tasks",
		update: "inbox/updates",
		reference: "wiki/references",
		idea: "inbox/ideas",
		conversation: "inbox/conversations",
		unclassified: "inbox/unclassified",
	},
	classificationPrompt: "",
	_apiCallsToday: 0,
	_apiCallsDate: "",
};
